"""Creat Table

Revision ID: 21c8012d2c97
Revises: 10d0eb272386
Create Date: 2023-10-23 15:24:31.198952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


# revision identifiers, used by Alembic.
revision = '21c8012d2c97'
down_revision = '10d0eb272386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass