"""Creat Table

Revision ID: 21c8012d2c97
Revises: 10d0eb272386
Create Date: 2023-10-23 15:24:31.198952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


# revision identifiers, used by Alembic.
revision = '21c8012d2c97'
down_revision = '10d0eb272386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', pg.INTEGER, nullable=False),
    sa.Column('name', pg.VARCHAR(32), nullable=False),
    sa.Column('created_at', pg.TIMESTAMP(timezone=True), server_default=sa.text("(DATETIME('now', 'localtime'))"), nullable=False),
    sa.Column('updated_at', pg.TIMESTAMP(timezone=True), server_default=sa.text("(DATETIME('now', 'localtime'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_table('todo',
    sa.Column('id', pg.INTEGER, nullable=False),
    sa.Column('content', pg.VARCHAR(256), nullable=False),
    sa.Column('completed', pg.BOOLEAN, server_default='False', nullable=False),
    sa.Column('deadline', pg.TIMESTAMP, nullable=True),
    sa.Column('created_at', pg.TIMESTAMP(timezone=True), server_default=sa.text("(DATETIME('now', 'localtime'))"), nullable=False),
    sa.Column('updated_at', pg.TIMESTAMP(timezone=True), server_default=sa.text("(DATETIME('now', 'localtime'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=False)
    op.create_table('todo_tag',
    sa.Column('todo_id', pg.INTEGER, nullable=False),
    sa.Column('tag_id', pg.INTEGER, nullable=False),
    sa.Column('created_at', pg.TIMESTAMP(timezone=True), server_default=sa.text("(DATETIME('now', 'localtime'))"), nullable=False),
    sa.Column('updated_at', pg.TIMESTAMP(timezone=True), server_default=sa.text("(DATETIME('now', 'localtime'))"), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('todo_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_tag')
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_table('todo')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
