"""empty message

Revision ID: 557f2838dcd8
Revises: cf796608283f
Create Date: 2023-11-13 15:10:58.116439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557f2838dcd8'
down_revision = 'cf796608283f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), server_default='IPUT', nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
