"""empty message

Revision ID: ca6e104db80f
Revises: e59f04331c0f
Create Date: 2023-11-07 14:23:14.826698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6e104db80f'
down_revision = 'e59f04331c0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
