"""empty message

Revision ID: e59f04331c0f
Revises: 2528d91131ee
Create Date: 2023-11-07 14:21:59.277211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59f04331c0f'
down_revision = '2528d91131ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
