"""empty message

Revision ID: f6fff35b7139
Revises: ca6e104db80f
Create Date: 2023-11-07 14:23:56.004807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fff35b7139'
down_revision = 'ca6e104db80f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
