pipeline {
    agent none
    environment {
        PROJECT_NAME="FastAPI+SQLArchemy Todo Sample"
        API_V1_STR="/v1"
        BACKEND_CORS_ORIGINS="localhost"
        DATABASE_URL="sqlite:///todo.db"
        LOGGING_CONF="./logging.json"
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.12.0-alpine3.18'
                }
            }
            steps {
                sh 'echo "Building the project"'
                sh 'cd practical-fastapi/src/test; python -m py_compile conftest.py'
                // stash(name: 'compiled-results', includes: 'practical-fast-api/src/test/*.py*')
            }
            post {
                success {
                    slackSend (color: 'success', message: "ビルドに成功しました")
                }
                unstable {
                    slackSend (color: 'warning', message: "ビルドが不安定です: ${env.JOB_NAME} - ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
                }
                failure {
                    slackSend (color: 'danger', message: "ビルドに失敗しました: ${env.JOB_NAME} - ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
                }
            }
        }
        stage('Test') {
            agent {
                dockerfile {
                    filename 'Jenkins/Dockerfile'
                    args '--network=default'
                }
            }
            steps {
                sh 'echo "Testing the project"'
                sh 'cd practical-fastapi; pytest'
            }
            post {
                success {
                    slackSend (color: 'success', message: "テストに成功しました: ${env.JOB_NAME} - ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
                }
                unstable {
                    slackSend (color: 'warning', message: "テストが不安定です: ${env.JOB_NAME} - ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
                }
                failure {
                    slackSend (color: 'danger', message: "テストに失敗しました: ${env.JOB_NAME} - ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
                }
            }
        }
    }
}